<a href="https://colab.research.google.com/github/stefanoconiglio/numpy_recap/blob/main/numpy_recap_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# The quickest Numpy recap on Earth

I'll try my best to make this as fast as possible. Some ideas came from here: http://chatgpt.com/c/68095add-712c-800c-bfe7-76f121bdc1d9
No, you can't access it. You don't want to read my swearing to ChatGPT. Trust me.

Rules: when the 1st line of a block does not have a comment, it's usually a boilerplate line where some variable is built for later use.

## Preliminaries (not numpy related)
This is just some inefficient madness to print the name of a variable long with its content. Don't use it in production. It's only for teaching purposes.

In [145]:
#VOODOO TO PRINT VAR NAME ALONG ITS CONTENT
import inspect

def nprint(var):
  """
  prints variable name along with its content
  """
  frame = inspect.currentframe().f_back
  names = [name for name in frame.f_code.co_names if frame.f_locals.get(name) is var]
  name = names[0] if names else 'var'
  print(f"{name}:\n {var}\n"+"-"*80)

## Part 1: the basics (1/2D arrays, indexing, broadcasting)

In [146]:
# IMPORT THE OBVIOUS
import numpy as np

In [147]:
# PYTHON LISTS

# this is a list
list_1d = [1,2,3,4,5,6,7,8,9]
nprint(list_1d)

# this is a list of lists
list_2d = [[1,2,3,4],[5,6,7,8]]
nprint(list_2d)

list_1d:
 [1, 2, 3, 4, 5, 6, 7, 8, 9]
--------------------------------------------------------------------------------
list_2d:
 [[1, 2, 3, 4], [5, 6, 7, 8]]
--------------------------------------------------------------------------------


In [148]:
# ARANGE -- array of a range

# from 0 to 20-1
a = np.arange(20)
nprint(a)

# from 10 to 20-1 with a step of 2
b = np.arange(10,20,2)
nprint(b)

a:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
--------------------------------------------------------------------------------
b:
 [10 12 14 16 18]
--------------------------------------------------------------------------------


In [149]:
# 1D ARRAY VS 2D ARRAY

# 1d array (rated from list)
a = np.array([1,2,3])
nprint(a)

# 2d array (created from list of lists)
b = np.array([[1,2,3],[4,5,6]])
nprint(b)

a2 = np.array([[1,2,3]])
nprint(a2)

a:
 [1 2 3]
--------------------------------------------------------------------------------
b:
 [[1 2 3]
 [4 5 6]]
--------------------------------------------------------------------------------
a2:
 [[1 2 3]]
--------------------------------------------------------------------------------


In [156]:
#SHAPE (= size, one per dim)

# shape of b: as expected: b is 2x3
nprint(b.shape)

# shape of a: odd: (3,) -- a tuple of a single element
nprint(a.shape)

# shape of a2: a2 is a 2d array even if the 1st dimension is 1
nprint(a2.shape)

var:
 (2, 3)
--------------------------------------------------------------------------------
var:
 (3,)
--------------------------------------------------------------------------------
var:
 (1, 3)
--------------------------------------------------------------------------------


In [157]:
# DIGRESSION ON SINGLE-ELEMENT TUPLES

#this is the way to define 1-tuples; if you do
t = (3)
nprint(type(t))
#you only get an integer whereas with
t = (3,)
nprint(type(t))
#you get a tuple

var:
 <class 'int'>
--------------------------------------------------------------------------------
var:
 <class 'tuple'>
--------------------------------------------------------------------------------


In [164]:
# RESHAPE

a = np.arange(20,103,2)
nprint(a)

# reshape
a_2 = a.reshape(6,7)
nprint(a_2)

a:
 [ 20  22  24  26  28  30  32  34  36  38  40  42  44  46  48  50  52  54
  56  58  60  62  64  66  68  70  72  74  76  78  80  82  84  86  88  90
  92  94  96  98 100 102]
--------------------------------------------------------------------------------
a_2:
 [[ 20  22  24  26  28  30  32]
 [ 34  36  38  40  42  44  46]
 [ 48  50  52  54  56  58  60]
 [ 62  64  66  68  70  72  74]
 [ 76  78  80  82  84  86  88]
 [ 90  92  94  96  98 100 102]]
--------------------------------------------------------------------------------


In [152]:
#ELEMENTWISE OPERATIONS

a += 10
nprint(a)

b *= 10
nprint(b)

a:
 [11 12 13]
--------------------------------------------------------------------------------
b:
 [[10 20 30]
 [40 50 60]]
--------------------------------------------------------------------------------


## Indexing

In [165]:
# SINGLE-ITEM INDEXING

nprint(b)
nprint(b[1][1]) # C-style list-of-list indexing
nprint(b[1,1])  # indexing-via-an-array

b:
 [[10 20 30]
 [40 50 60]]
--------------------------------------------------------------------------------
var:
 50
--------------------------------------------------------------------------------
var:
 50
--------------------------------------------------------------------------------


In [154]:
# FANCY INDEXING: index with array of arrays
# - 1st array: row indices
# - 2nd array: col indices
# - 3rd array: ...

c = np.array(['a','b','c','d','e','f','g','h','i','l'])

# recover items at position 1,5,9
c_1 = c[[1,5,9]]
nprint(c_1)

# this fancy indexes in c with the list of even indexes numbers
# using list comprehension
c_2 = c[[j for j in range(len(c)) if j % 2 == 0]]
nprint(c_2)

# 2d array of items from 10 to 20 with list comprehension
d = np.array([[j for j in range(1,11)],[j for j in range(11,21)]])
nprint(d)

d_1 = d[[0,1],[3,4]] #takes rows 0,1 and item 3 from row 0 and item 4 from row 4
nprint(d_1)

d_2 = d[[0,1],[3,]] #the single col index 3 is broacast also to he 2nd row
nprint(d_2)

# get the FULL cols 3 and 4 of a matrix
e = np.arange(20).reshape(5,4)
nprint(e)

e_1 = e[:,[1,2]]
nprint(e_1)

c_1:
 ['b' 'f' 'l']
--------------------------------------------------------------------------------
c_2:
 ['a' 'c' 'e' 'g' 'i']
--------------------------------------------------------------------------------
d:
 [[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]
--------------------------------------------------------------------------------
d_1:
 [ 4 15]
--------------------------------------------------------------------------------
d_2:
 [ 4 14]
--------------------------------------------------------------------------------
e:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
--------------------------------------------------------------------------------
e_1:
 [[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]
 [17 18]]
--------------------------------------------------------------------------------


In [155]:
# BOOLEAN MASKS

e = np.array([j for j in range(0,11)])

# mask of even indices
mask = e % 2 == 0
nprint(mask)

e_1 = e[mask]
nprint(e_1)

mask:
 [ True False  True False  True False  True False  True False  True]
--------------------------------------------------------------------------------
e_1:
 [ 0  2  4  6  8 10]
--------------------------------------------------------------------------------
