<a href="https://colab.research.google.com/github/stefanoconiglio/numpy_recap/blob/main/numpy_recap_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# The quickest Numpy recap on Earth

I'll try my best to make this as fast as possible. Some ideas came from here: http://chatgpt.com/c/68095add-712c-800c-bfe7-76f121bdc1d9
No, you can't access it. You don't want to read my swearing to ChatGPT. Trust me.

Rules: when the 1st line of a block does not have a comment, it's usually a boilerplate line where some variable is built for later use.

## Preliminaries (not numpy related)
This is just some inefficient madness to print the name of a variable long with its content. Don't use it in production. It's only for teaching purposes.

In [1]:
#VOODOO TO PRINT VAR NAME ALONG ITS CONTENT
import inspect

# def nprint(var):
#   """
#   prints variable name along with its content
#   """
#   frame = inspect.currentframe().f_back
#   names = [name for name in frame.f_code.co_names if frame.f_locals.get(name) is var]
#   name = names[0] if names else 'var'
#   print(f"{name}:\n {var}\n"+"-"*80)

import inspect
import ast

def nprint(var):
    # Get the previous frame (caller)
    frame = inspect.currentframe().f_back
    # Get the line of code that called this function
    try:
        source_line = inspect.getframeinfo(frame).code_context[0]
    except Exception:
        source_line = None

    # Try to parse the argument name (best effort!)
    if source_line:
        # Find the argument inside the parentheses
        arg_text = source_line.split('nprint(', 1)[1].split(')', 1)[0]
    else:
        arg_text = 'var'
    print(f"{arg_text}:\n {var}\n"+"-"*80)

In [2]:
# IMPORT THE OBVIOUS
import numpy as np

## Creation of 1D, 2D, and $k$-D arrays from Python lists and understanding their `shape`

In [3]:
# PYTHON LISTS

# this is a list
list_1d = [1,2,3,4,5,6,7,8,9]
nprint(list_1d)

# this is a list of lists
list_2d = [[1,2,3,4],[5,6,7,8]]
nprint(list_2d)

list_3d = [[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]
nprint(list_3d)

list_1d:
 [1, 2, 3, 4, 5, 6, 7, 8, 9]
--------------------------------------------------------------------------------
list_2d:
 [[1, 2, 3, 4], [5, 6, 7, 8]]
--------------------------------------------------------------------------------
list_3d:
 [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]
--------------------------------------------------------------------------------


In [4]:
# NP 1D ARRAYS VS 2D ARRAYS AND SHAPE
# shape = size, one per dim; a dim is called an AXIS in Numpy
# for a 3d array, axis0 = depth, axis1 = rows, axis2 = cols

# 1d array (from list)
a_1d_3x = np.array([1,2,3])
nprint(a_1d_3x)

# this returns (3,) -- see further why
nprint(a_1d_3x.shape)

# 2d array of size 3x1 (from list of a single list)
a_2d_3x1 = np.array([[1,2,3]])
nprint(a_2d_3x1)

# this returns (3,) -- see further why
nprint(a_2d_3x1.shape)

# 2d array (created from list of lists)
a_2d_3x2 = np.array([[1,2,3],[4,5,6]])
nprint(a_2d_3x2)

# this returns (3,2), as expected
nprint(a_2d_3x2.shape)

a_2d_1x3 = np.array([[1,2,3]])
nprint(a_2d_1x3)

# this returns (1,3), as expected
nprint(a_2d_1x3.shape)

# 3d array of size 3x2x4
a_3d_3x2x4 = np.array([[[1,2,12,0],[3,4,34,0]],[[5,6,56,0],[7,8,78,0]],
  [[9,10,910,0],[11,12,1112,0]]])
nprint(a_3d_3x2x4)

# depth 4, rows 2, cols 4
nprint(a_3d_3x2x4.shape)

a_1d_3x:
 [1 2 3]
--------------------------------------------------------------------------------
a_1d_3x.shape:
 (3,)
--------------------------------------------------------------------------------
a_2d_3x1:
 [[1 2 3]]
--------------------------------------------------------------------------------
a_2d_3x1.shape:
 (1, 3)
--------------------------------------------------------------------------------
a_2d_3x2:
 [[1 2 3]
 [4 5 6]]
--------------------------------------------------------------------------------
a_2d_3x2.shape:
 (2, 3)
--------------------------------------------------------------------------------
a_2d_1x3:
 [[1 2 3]]
--------------------------------------------------------------------------------
a_2d_1x3.shape:
 (1, 3)
--------------------------------------------------------------------------------
a_3d_3x2x4:
 [[[   1    2   12    0]
  [   3    4   34    0]]

 [[   5    6   56    0]
  [   7    8   78    0]]

 [[   9   10  910    0]
  [  11   12 1112    0]]]
------

In [5]:
# DIGRESSION ON SINGLE-ELEMENT TUPLES

#this is the way to define 1-tuples; if you do
t = (3)
nprint(type(t))
#you only get an integer whereas with
t = (3,)
nprint(type(t))
#you get a tuple

type(t:
 <class 'int'>
--------------------------------------------------------------------------------
type(t:
 <class 'tuple'>
--------------------------------------------------------------------------------


## Array creation routines

In [6]:
# ARANGE -- array of a range: INT sequences

# from 0 to 20-1
a = np.arange(20)
nprint(a)

# from 10 to 20-1 with a step of 2
b = np.arange(10,20,2)
nprint(b)

# TODO:
# - np.ogrid
# - np.mgrid

# USING LIST COMPREHENSION

# 2d array of items from 10 to 20 with list comprehension
d = np.array([[j for j in range(1,11)],[j for j in range(11,21)]])
nprint(d)

a:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
--------------------------------------------------------------------------------
b:
 [10 12 14 16 18]
--------------------------------------------------------------------------------
d:
 [[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]
--------------------------------------------------------------------------------


In [7]:
# LINSPACE: FP sequences

init, end, qty = 20, 8, 10
a_inc = np.linspace(init, end, qty)
nprint(a_inc)

init, end, qty = 8, 20, 10
a_dec = np.linspace(init, end, qty)
nprint(a_dec)

a_inc:
 [20.         18.66666667 17.33333333 16.         14.66666667 13.33333333
 12.         10.66666667  9.33333333  8.        ]
--------------------------------------------------------------------------------
a_dec:
 [ 8.          9.33333333 10.66666667 12.         13.33333333 14.66666667
 16.         17.33333333 18.66666667 20.        ]
--------------------------------------------------------------------------------


## Some notable (math) matrices

In [8]:
# NOTABLE (NAMED) MATH MATRICES

a = np.zeros((2,10))
nprint(a)

b = np.ones((2,3))
nprint(b)

c = np.eye(4)
nprint(c)

d = np.diag([1,2,3,4])
nprint(d)

e = np.vander(np.arange(5))
nprint(e)

f = np.random.rand(3,4)
nprint(f)

g = np.random.randn(3,4)
nprint(g)

a:
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
--------------------------------------------------------------------------------
b:
 [[1. 1. 1.]
 [1. 1. 1.]]
--------------------------------------------------------------------------------
c:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
--------------------------------------------------------------------------------
d:
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
--------------------------------------------------------------------------------
e:
 [[  0   0   0   0   1]
 [  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]]
--------------------------------------------------------------------------------
f:
 [[0.07379963 0.7211526  0.71604837 0.81232281]
 [0.33319667 0.55699033 0.74978068 0.22711823]
 [0.60119403 0.02382355 0.21051746 0.1122486 ]]
--------------------------------------------------------------------------------
g:
 [[ 0.98437027  1.06466493 -0.9

## Reshape

In [9]:
# RESHAPE

d = np.arange(20)
nprint(d)

# from 20x1 to 5x4
d_2 = d.reshape(5,4)
nprint(d_2)

# from 20x1 to 2x? (? is autocomputed)
d_3 = d.reshape(2,-1)
nprint(d_3)

# a fail case (3 doesn't divide 20)
d_3 = d.reshape(3,-1)
nprint(d_3)


d:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
--------------------------------------------------------------------------------
d_2:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
--------------------------------------------------------------------------------
d_3:
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
--------------------------------------------------------------------------------


ValueError: cannot reshape array of size 20 into shape (3,newaxis)

## Indexing

In [10]:
# SINGLE-ITEM INDEXING

a = np.array([[1,2,3],[4,5,6]])

nprint(a)
nprint(a[1][1]) # C-style list-of-list indexing
nprint(a[1,1])  # indexing-via-an-array

a:
 [[1 2 3]
 [4 5 6]]
--------------------------------------------------------------------------------
a[1][1]:
 5
--------------------------------------------------------------------------------
a[1,1]:
 5
--------------------------------------------------------------------------------


In [11]:
# FANCY INDEXING IN THE 1D CASE: index with an array of the indices you want

c = np.array(['a','b','c','d','e','f','g','h','i','l'])
nprint(c)

# recover items at position 1,5,9
c_1 = c[[1,5,9]]
nprint(c_1)

# this fancy indexes in c with the list of even indexes numbers
# using list comprehension
c_2 = c[[j for j in range(len(c)) if j % 2 == 0]]
nprint(c_2)


c:
 ['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i' 'l']
--------------------------------------------------------------------------------
c_1:
 ['b' 'f' 'l']
--------------------------------------------------------------------------------
c_2:
 ['a' 'c' 'e' 'g' 'i']
--------------------------------------------------------------------------------


In [12]:
# FANCY INDEXING IN THE 2D CASE: index with two same-size arrays, one of row
# indices, one of col indices: (A[[1,2],[3,4]] gives A[1,3] and A[2,4])

d = np.arange(20).reshape(5,4)
nprint(d)

# return items [0,2],[1,3],[2,1]
d_1 = d[[0,1,2],[2,3,1]]
nprint(d_1)

# here the single col index 2 is broacast to every col
d_2 = d[[0,1,2],[2,]]
nprint(d_2)

d:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
--------------------------------------------------------------------------------
d_1:
 [2 7 9]
--------------------------------------------------------------------------------
d_2:
 [ 2  6 10]
--------------------------------------------------------------------------------


In [13]:
# SLICING: INDEX-CONTIGUOUS SUBMATRICES

# SLICING INDEXING: 1D

a = np.arange(20,40,2)
nprint(a)

# items from 2 to 5-1
a_slice = a[2:5]
nprint(a_slice)

# SLICING INDEXING: 2D

b = np.arange(10,40).reshape(6,-1)
nprint(b)

# rows 2 to 5
b_row_slice = b[2:5]
nprint(b_row_slice)

# cols 1 to 3-1
b_col_slice = b[:,1:3]
nprint(b_col_slice)

# rows 2 to 5-1 and cols 1 to 3-1
b_row_col_slice = b[2:5,1:3]
nprint(b_row_col_slice)

# SLICE INDEXING: 3D

c = np.arange(0,180).reshape(5,4,-1)
nprint(c)

# depth 1 to 3-1, rows 1 to 4-1, cols 1 to 3-1
c_depth_row_col_slice = c[1:3,1:4,1:3]
nprint(c_depth_row_col_slice)

a:
 [20 22 24 26 28 30 32 34 36 38]
--------------------------------------------------------------------------------
a_slice:
 [24 26 28]
--------------------------------------------------------------------------------
b:
 [[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]]
--------------------------------------------------------------------------------
b_row_slice:
 [[20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]]
--------------------------------------------------------------------------------
b_col_slice:
 [[11 12]
 [16 17]
 [21 22]
 [26 27]
 [31 32]
 [36 37]]
--------------------------------------------------------------------------------
b_row_col_slice:
 [[21 22]
 [26 27]
 [31 32]]
--------------------------------------------------------------------------------
c:
 [[[  0   1   2   3   4   5   6   7   8]
  [  9  10  11  12  13  14  15  16  17]
  [ 18  19  20  21  22  23  24  25  26]
  [ 27  28  29  30  31  32  33  34  

In [14]:
# SUBMATRIX INDEXING WITH IX_

a = np.arange(20).reshape(5,-1)
nprint(a)

# rows 0,1,2; cols 1,3
a_sub = a[np.ix_([0,1,2],[1,3])]
nprint(a_sub)

# rows 0,1; cols 1,3
a_sub_square = a[np.ix_([0,1,2],[0,1,3])]
nprint(a_sub_square)

# notice diff with similar indexing using fancy indexing
a_fancy = a[[0,1,2],[0,1,3]]
nprint(a_fancy)

a:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
--------------------------------------------------------------------------------
a_sub:
 [[ 1  3]
 [ 5  7]
 [ 9 11]]
--------------------------------------------------------------------------------
a_sub_square:
 [[ 0  1  3]
 [ 4  5  7]
 [ 8  9 11]]
--------------------------------------------------------------------------------
a_fancy:
 [ 0  5 11]
--------------------------------------------------------------------------------


In [16]:
# FANCY INDEXING VS ix_
# - Fancy indexing pairs one-to-one rows and col idx
# - ix_ creates all pairs

a = np.arange(20).reshape(5,-1)
nprint(a)

# fancy indexing
a_2 = a[[0,1,3],[1,2,3]]
nprint(a_2)

# ix_
a_3 = a[np.ix_([0,1,3],[1,2,3])]
nprint(a_3)

a:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
--------------------------------------------------------------------------------
a_2:
 [ 1  6 15]
--------------------------------------------------------------------------------
a_3:
 [[ 1  2  3]
 [ 5  6  7]
 [13 14 15]]
--------------------------------------------------------------------------------


In [15]:
# SUBMATRIX WITH SLICING AND FANCY INDEXING

a = np.arange(20).reshape(5,-1)
nprint(a)

# rows 2 and 3, all cols
a_sub = a[[2,3], :]
nprint(a_sub)

# same
a_sub2 = a[[2,3]]
nprint(a_sub2)

# all rows, cols 1 and 2
a_sub3 = a[:, [1,2]]
nprint(a_sub3)

a:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
--------------------------------------------------------------------------------
a_sub:
 [[ 8  9 10 11]
 [12 13 14 15]]
--------------------------------------------------------------------------------
a_sub2:
 [[ 8  9 10 11]
 [12 13 14 15]]
--------------------------------------------------------------------------------
a_sub3:
 [[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]
 [17 18]]
--------------------------------------------------------------------------------


In [17]:
# BOOLEAN MASKING

e = np.array([j for j in range(0,11)])

# mask of even indices
mask = e % 2 == 0
nprint(mask)

e_1 = e[mask]
nprint(e_1)

mask:
 [ True False  True False  True False  True False  True False  True]
--------------------------------------------------------------------------------
e_1:
 [ 0  2  4  6  8 10]
--------------------------------------------------------------------------------


## Axis expansion

In [18]:
# ADD EXTRA DIMS (AXIS) TO AN ARRAY

a = np.arange(20).reshape(5,-1)
nprint(a)
nprint(a.shape)

# add new 0th axis
a_exp = a[None,:]
nprint(a_exp)
nprint(a_exp.shape)

# add new 1st axis
a_exp2 = a[:,None]
nprint(a_exp2)
nprint(a_exp2.shape)

# add new 2nd axis
a_exp3 = a[:,:,None]
nprint(a_exp3)
nprint(a_exp3.shape)

a:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
--------------------------------------------------------------------------------
a.shape:
 (5, 4)
--------------------------------------------------------------------------------
a_exp:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]
  [16 17 18 19]]]
--------------------------------------------------------------------------------
a_exp.shape:
 (1, 5, 4)
--------------------------------------------------------------------------------
a_exp2:
 [[[ 0  1  2  3]]

 [[ 4  5  6  7]]

 [[ 8  9 10 11]]

 [[12 13 14 15]]

 [[16 17 18 19]]]
--------------------------------------------------------------------------------
a_exp2.shape:
 (5, 1, 4)
--------------------------------------------------------------------------------
a_exp3:
 [[[ 0]
  [ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]
  [ 7]]

 [[ 8]
  [ 9]
  [10]
  [11]]

 [[12]
  [13]
  [14]
  [15]]

 [[16]
  [17]
  [18]
  [19]]]
--------------------

## Transposition

In [ ]:
# with .T

# does nothing to (n,) arrays
a_n_ = np.arange(10)
nprint(a_n_)

# see?
a_n_T = a_n_.T
nprint(a_n_T)

# works on (n,1) arrays
a_n_1 = np.arange(10).reshape(10,-1)
nprint(a_n_1)

# see?
a_n_1_T = a_n_1.T
nprint(a_n_1_T)

In [ ]:
# with axis expansion (cheating)

a = np.arange(20)
nprint(a)
nprint(a.shape)

a_T = a[:,None]
nprint(a_T)

x = np.arange(3)    # shape (3,)
nprint(x)
y = np.arange(2)    # shape (2,)
nprint(y)

z = x[None, :] + y[:, None]   # shape (2,3)
nprint(z)

xx = x[None, :]
nprint(xx)
yy = y[:, None]
nprint(yy)

## Broadcasting

In [ ]:
# BROADCASTING = AUTO SHAPE EXPANSION OF A SMALL MATRIX OPERATED WITH A BIG ONE

a = np.arange(20).reshape(5,-1)
nprint(a)

# SCALAR BROADCAST

a_2 = a + 10
nprint(a_2)

a_3 = a * 10
nprint(a_3)

# (n,) TO (n,1) BROADCAST

a_1d = np.arange(20)
nprint(a_1d)
nprint(a_1d.shape)

a_2d = np.arange(20,40).reshape(1,-1)
nprint(a_2d)
nprint(a_2d.shape)

# here is the sum
a_sum_vec = a_1d + a_2d
nprint(a_sum_vec)

# (n,1) to (1,m) BROADCAST

a_n_1 = np.arange(3).reshape(3,-1)
nprint(a_n_1)

a_1_n = np.arange(5,10).reshape(1,-1)
nprint(a_1_n)

# sum row by row with row of a_n_1 (scalar) broadcast
a_sum_matr = a_1_n + a_n_1
nprint(a_sum_matr)